### ISSUE TITLE
Bug：把地点标记为隐藏不会使它在地图上消失

### ISSUE THREAD

**Issue by AsterNighT** [elpwc/EldenRingOnlineMap#1]
把地点标记为隐藏不会使它在地图上消失，需要刷新一次，或是点上显示隐藏再去掉，才能使标记隐藏。

期望表现：将地点标记为隐藏时，地点从地图上消失。
实际表现：将地点标记为隐藏时，地点会在下一次加载时消失。

**Comment by elpwc** [comment]
算是写的时候偷懒了（
下次更新改正

**Comment by elpwc** [comment]
修复啦
![alt yadaze](https://www.elpwc.com/imagebank/ureshisounaemu.jpg)
