### ISSUE TITLE
Markers are not displayed

### ISSUE THREAD

**Issue by Abbadon999** [elpwc/EldenRingOnlineMap#16]
I'm just a beginner, so it's hard for me to understand the whole compilation sequence 
After "npm run build", markers are not displayed, did I miss some point?
I ran the map through "index.html"
![image](https://user-images.githubusercontent.com/42169608/160150010-9e013010-75a3-4991-9264-fc8c4966d584.png)
After I created the database through phpmyadmin and transferred the "public" folder to the projects.
But it didn't work, and now I'm getting this error
![image](https://user-images.githubusercontent.com/42169608/160233949-03288f70-a96a-4717-99a9-0c779882ce39.png)

I also tried to run the map through the "npm run dev" command, and in this case, some markers appeared, but for some reason I could not change anything: When I created custom markers, they disappeared after reloading the page ..

**Comment by elpwc** [comment]
It's hard to say if it's a php problem or a mysql problem without showing php's response data,
You can find response data from `press F12 in browser`→`Network`→`map.php?type=...`→`Response` after reloading page.

**Comment by Abbadon999** [comment]
Well, there is some kind of warning message here.
![image](https://user-images.githubusercontent.com/42169608/160269491-52e5da4b-57fb-409b-9acb-76a59d9f1abf.png)
![image](https://user-images.githubusercontent.com/42169608/160269498-d3876aac-b25a-404d-ad33-340f46ae6a0e.png)
MySQL I connected  
![image](https://user-images.githubusercontent.com/42169608/160272185-ae0b109a-12ef-4d97-bf71-b3eae8ae35aa.png)
But now I'm getting a warning about the file "ipRequest.php" 
![image](https://user-images.githubusercontent.com/42169608/160272257-1f3a1637-9b72-4bf2-a199-101b7d03f40b.png)

**Comment by spking11** [comment]
> Well, there is some kind of warning message here. 

Probably because you run `npm dev`, this is for development. It will build `bundle.js` with a mock service which is just for the front-end test, it will intercept connections to the backend, then return mock data.
Just run `npm build` and ensure the `bundle.js` is compressed, this indicates it built for production.

**Comment by Abbadon999** [comment]
After configuring "dbcfg.php" I tried using npm build command and ran \public\index.html accordingly
The map itself opens, but there are no markers, and I also cannot create my own markers, since the button to complete the creation is not pressed. Also, I can't get the admin, because when entering the password, the "ok" button is also not pressed 

![image](https://user-images.githubusercontent.com/42169608/160273363-c04dca30-b4e3-47c8-ba55-c4f82d8610b3.png)
Could it be related to MySQL?

**Comment by elpwc** [comment]
As you can see the error shows ***...are only supported for protocal schemes: http, ...***  
Request sent to php files should be via 'http' but not 'file', before this, you have to start an Apache server (and other php runtime environment stuff) in your computer and navigate to the webpage by http://localhost:xxxx. (xxxx→port  

> Could it be related to MySQL?  

Currently it obviously causes by a not installed/incorrectly installed php environment.

**Comment by Abbadon999** [comment]
So, as you said, I launched the site through Apache, you can see it in the address bar, but now I get this error: 
![image](https://user-images.githubusercontent.com/42169608/160370224-b538c259-ef24-4e5d-8931-08b92f1e3368.png)
![image](https://user-images.githubusercontent.com/42169608/160370586-624affdd-58a1-4258-bf50-bd7f98ada2d1.png)
As I see it, this is most likely related to MySQL, but I don’t understand what I did wrong..

**Comment by elpwc** [comment]
Seems caused by Google Analytics and Baidu Analytics codes (intercepted by ads blocker in your browser)  
You can delete these analytics codes in index.html and then have a try, good luck!  

```html

  <script>
    var _hmt = _hmt || [];
    (function () {
      var hm = document.createElement('script');
      hm.src = 'https://hm.baidu.com/hm.js?36c2817b0416712d9807ee55315eaf4f';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(hm, s);
    })();
  </script>

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-SP07Q8CYM7"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'G-SP07Q8CYM7');
  </script>

  <!--Google AdSense-->
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1195280671714046"
    crossorigin="anonymous"></script>
```

**Comment by Abbadon999** [comment]
Now my card is broken and the error message still persists
![image](https://user-images.githubusercontent.com/42169608/160379445-a7982286-c7b5-416a-8187-fc4c48e1e6ce.png)

**Comment by elpwc** [comment]
Seems like your server is not able to visit the map data(?
Try to visit https://imgs.ali213.net/picfile/eldenring/4/6/6.jpg on your server

**Comment by Abbadon999** [comment]
I'm sorry, I accidentally deleted more lines of code, now everything loads without errors, but when creating a marker, this message will still appear: 
![image](https://user-images.githubusercontent.com/42169608/160385017-653e1b6f-7042-4e73-bff6-a13bb003a4b7.png)

**Comment by elpwc** [comment]
Oh... I'm so sorry, I forgot to add the 'is_lock' column into database.sql...   
you can append this column by:  

```mysql
ALTER TABLE `eldenringmap`.`map` 
ADD COLUMN `is_lock` TINYINT(1) NULL DEFAULT '0';
```

and then it probably works

**Comment by Abbadon999** [comment]
Error remained
![image](https://user-images.githubusercontent.com/42169608/160388677-2655f910-cd73-4b4b-a389-240e41ded257.png)
![image](https://user-images.githubusercontent.com/42169608/160388765-194e3226-630b-4473-ab91-4bef82afa109.png)

**Comment by elpwc** [comment]
Try to find the method error occured in `map.php` and add a `@` in the front of the method.

**Comment by Abbadon999** [comment]
Sorry, my mistake.. I repeat that I'm just a beginner..
But I did it! Thank you very much for helping!

**Comment by elpwc** [comment]
Awesome!
Never mind it!
