### ISSUE TITLE
English version pls

### ISSUE THREAD

**Issue by CZTeo** [elpwc/EldenRingOnlineMap#2]
English version would be appreciated i tried to google translate the website but the icons dont show up on map

**Comment by elpwc** [comment]
I was thinking about to add an English version, but as I know there're several similar English sites already exist, I don't know if this could be widely used by English-speaking players now. Also, after English version added, Chinese markers won't be retained, as they're difficult to translate.
If there's really a needs for user-editabe EldenRing map, I'd be pleasure to add an English version.
