### ISSUE TITLE
是否可以为地上和地下的物体做一下区分

### ISSUE THREAD

**Issue by yearning328** [elpwc/EldenRingOnlineMap#22]
比如搜索锻造石X或者墓地铃兰X，出来的地图标识经常不知道是地上的还是地下的，花费很多无用功。

**Comment by elpwc** [comment]
已经区分了（）  
但因为是前几天刚刚加入的，所以还有很多物品没有编辑到地下

https://github.com/elpwc/EldenRingOnlineMap/commit/b6299b7df084d9c1e1d9221fe535b85cc8cb70e6
