### ISSUE TITLE
Positioning of the Marker

### ISSUE THREAD

**Issue by Abbadon999** [elpwc/EldenRingOnlineMap#24]
The positioning of the marker and cursor is not clear to me, I would like to set the marker more accurately. Just after setting the marker, it is shifted to the right relative to the cursor. It seems that the anchor(main point) to the upper left corner of the marker image. I also noticed that when the map is zoomed in, the markers move from the starting point

**Comment by elpwc** [comment]
Yes I didn't add an icon archor to icons, for icons using images(not emojis), you can add iconSize and iconArchor in `src/components/icons.ts` for each member in MapIcon object:

```ts
      ....
      return {
        html: `
        <div class="icon">
        ......
        </div>
    `,
        className: '',
        iconSize: [size, size],
        iconArchor: [size / 2, size / 2],
      };
```

**Comment by elpwc** [comment]
Yes I didn't add archors to icons, and I just add it  
You can find my changes in:https://github.com/elpwc/EldenRingOnlineMap/commit/f3ec524324324121c9d9dd0e5089679cf96ebc40

**Comment by Abbadon999** [comment]
Markers are now more convenient to put, thank you very much! But I have one more suggestion regarding markers: When I zoom the map the markers get larger as I zoom out, and I would like them to be able to lock in at about half their size even if I zoom out the map as far as possible. It's just that when I zoom out the map, the markers take up too much space on the screen.
In general, to put it simply - is it possible to make the markers not constantly increase when moving away?

**Comment by elpwc** [comment]
Make sense. I've tried to achieve this, but it's a little hard for me and I don't have much time to continue it. Maybe you can see some about `map cluster`, this could be the way to achieve your idea. (If my comprehension is not wrong)
Anyway, thanks for having interest in my project!
