### ISSUE TITLE
左边显示选项有异常

### ISSUE THREAD

**Issue by ksyou945** [elpwc/EldenRingOnlineMap#25]
![截图20220330132105](https://user-images.githubusercontent.com/102645591/160756957-d53eb315-06cc-4a71-aaa6-f7d787fa181a.png)
![截图20220330132118](https://user-images.githubusercontent.com/102645591/160756968-941f31de-3524-40e3-b8af-c793636d8b69.png)

**Comment by elpwc** [comment]
这里没能复现成功
可以的话能不能看下F12里的报错
还有筛选选项的css样式(不会的话先发一下报错

**Comment by ksyou945** [comment]
![截图20220331062604](https://user-images.githubusercontent.com/102645591/160941288-45075ba7-197e-4ff3-af7c-3239de59e8bd.png)

**Comment by ksyou945** [comment]
不知道这个是不是

**Comment by elpwc** [comment]
确实是这个
但从这个信息来看问题不出在这，更可能是浏览器本身对竖排的渲染支持有问题
我根据猜想试着修复了一下，麻烦再看看还是这样的情况吗
