### ISSUE TITLE
本地部署后没有点位

### ISSUE THREAD

**Issue by karaikyo** [elpwc/EldenRingOnlineMap#36]
是我部署的有问题还是点位数据没有包含在repo里啊？

**Comment by elpwc** [comment]
数据当然是在服务器mysql数据库里的——
你需要本地部署一下自己的mysql和php环境

**Comment by karaikyo** [comment]
本地的mysql和php都部署好了（之前没弄好的时候网页会弹出一个从后台获取数据失败的窗口，部署后没了，应该是可以了吧？），但是表都是空的，地图上一个标点都不显示……这是部署出问题了吗？

**Comment by elpwc** [comment]
表的内容是需要自己写入的呀——

**Comment by karaikyo** [comment]
这样的话本地部署只能用来开发了……想使用的话没有点位数据部署了感觉也没什么用

**Comment by elpwc** [comment]
嘶...改天我可以提供个API文档
不过还是先等我升级完服务器吧orz

**Comment by t-liu93** [comment]
> 本地的mysql和php都部署好了（之前没弄好的时候网页会弹出一个从后台获取数据失败的窗口，部署后没了，应该是可以了吧？），但是表都是空的，地图上一个标点都不显示……这是部署出问题了吗？

想请问一下你是怎么成功部署本地mysql和php的？我这边已经初始化好mysql了，php的话我还有别的网页运行应当也是好的，部署了静态网页之后还是会有获取数据失败的窗口。cfg文件都已经编辑过了，似乎前端无法连接到数据库。
我是用nginx反向代理的
谢谢

**Comment by karaikyo** [comment]
> > 本地的mysql和php都部署好了（之前没弄好的时候网页会弹出一个从后台获取数据失败的窗口，部署后没了，应该是可以了吧？），但是表都是空的，地图上一个标点都不显示……这是部署出问题了吗？
> 
> 想请问一下你是怎么成功部署本地mysql和php的？我这边已经初始化好mysql了，php的话我还有别的网页运行应当也是好的，部署了静态网页之后还是会有获取数据失败的窗口。cfg文件都已经编辑过了，似乎前端无法连接到数据库。 我是用nginx反向代理的 谢谢

我没用ngnix……就在apache的httpd.conf里加了一段
`# PHP8 module`
`PHPIniDir "D:\dev\php-8.1.5-Win32-vs16-x64"`
`LoadModule php_module "D:\dev\php-8.1.5-Win32-vs16-x64\php8apache2_4.dll"`
`AddType application/x-httpd-php .php`
然后在php.ini里改了些目录设置，启用了mysqli和mbstring两个extension，试了一下添加标点数据库里能成功保存了
