### ISSUE TITLE
赞踩多次点击会一直增加计数

### ISSUE THREAD

**Issue by karaikyo** [elpwc/EldenRingOnlineMap#38]
误点了个踩，然后下意识又点了一下以为能取消，结果变成了两个踩。是否方便优化一下点击逻辑，比如改成第一次点+1，再点取消？

**Comment by elpwc** [comment]
因为没有账号系统，所以实现起来稍微麻烦一些，就算全部存在cookie里也挺鸡肋的(?)，另外最近备考没有精力继续开发了orz
如果不小心点错踩的话，就再顺便多点几个好评吧（
